# in this yaml you should add dependencies that are not included in the python packages
# (or that you want to install anyways such as torch to install cuda w/ conda)
# also make sure to install the local packages with the "-e" prefix
# to create an environment: conda env create -f environment.yaml
# to update: conda env update -f environment.yaml
name: dsd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - pytest
    - pre-commit
    - mypy
    - -e dsd/
    - -e airo-blender/airo-mono/airo-dataset-tools/
    - -e airo-blender/airo-mono/airo-typing/
    - -e airo-blender/airo-mono/airo-spatial-algebra/
    - -e airo-blender/
